apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: group-wordpress
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "SuperSecretRoot123!"
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "WordpressPass123!"
  MYSQL_DATABASE: "wordpress"